services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 20s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-init/servers.json:/pgadmin4/servers.json
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - postgres

  task_manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      POSTGRESQL_DB_HOST: postgres
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data: