services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-init/servers.json:/pgadmin4/servers.json
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: